# Generated by Django 3.1.3 on 2020-11-12 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_ingredients', '0002_ownedingredient_tip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownedingredient',
            old_name='ingredient_name',
            new_name='ingredient',
        ),
    ]
