# Generated by Django 3.1.3 on 2020-11-13 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_ingredients', '0003_auto_20201112_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownedingredient',
            old_name='tip',
            new_name='note',
        ),
    ]
